# Generated by Django 6.0.5 on 2026-05-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formdefaults", "0002_django32"),
    ]

    operations = [
        migrations.AddField(
            model_name="formrepresentation",
            name="pre_registered",
            field=models.BooleanField(
                default=False,
                help_text="True jeśli formularz został zarejestrowany dekoratorem @register_form lub przez setting FORMDEFAULTS_FORMS.",
                verbose_name="Zarejestrowany przez pre-rejestrację",
            ),
        ),
    ]
