# Generated by Django 6.0.5 on 2026-05-10 04:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formdefaults", "0003_formrepresentation_pre_registered"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="formfielddefaultvalue",
            index=models.Index(fields=["parent", "user"], name="fd_parent_user_idx"),
        ),
        migrations.AddConstraint(
            model_name="formfielddefaultvalue",
            constraint=models.UniqueConstraint(
                fields=("field", "user"), name="fd_unique_field_user"
            ),
        ),
    ]
