# Generated by Django 6.0.5 on 2026-05-10 04:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formdefaults", "0004_unique_field_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="formfielddefaultvalue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", True)),
                fields=("field",),
                name="fd_unique_field_system",
            ),
        ),
    ]
